### PR TITLE
Fix name for formatted address

### PR DESCRIPTION
**Pull request by flavian-iapp**

### CODE REVIEW

**Comment by moczix** [comment]
why did you changed it? javascript conventions use camelCase not underscore^^ so formattedAddress was good

**Comment by flavian-iapp** [comment]
Because, ios version of plugin use "formatted_address". It's better if both are similar

**Comment by moczix** [comment]
yep its better. But you use this plugin in javascript side in android and ios so its should be camel case in ios too

**Comment by ushu** [comment]
@flavian-iapp For now on I will close this PR and will probably re-add this change later.

The rationale is:

- it's probably a good idea to come closer the the [Javascript API](https://developers.google.com/maps/documentation/javascript/places) to ease the integration with existing JS code
- but right now I don't intend to break the API to incorporate this change.

*I will start a new branch this week* and start updating the API to mach the Javascript version, it will be breaking changes to it will imply a major version bump.

**Pull request closed without merging**
